@DashboardAPI_HostAddress = http://localhost:5237/api
@playerId = Player123

### Get Player Activities
GET {{DashboardAPI_HostAddress}}/players/{{playerId}}/activities
Accept: application/json

### Create Player Activity
POST {{DashboardAPI_HostAddress}}/players/{{playerId}}/activity
Content-Type: application/json

{
  "action": "Move",
  "timestamp": "2023-11-12T15:45:00Z"
}